# Flic
- platform: flic

# Nighttime
- platform: tod
  unique_id: nighttime
  name: Nighttime
  after: "00:00"
  before: "07:00"

# Quiet time
- platform: tod
  unique_id: quiet_time
  name: Quiet Time
  after: "22:00"
  before: "08:00"
